### ISSUE TITLE
Per-instance colors

### ISSUE THREAD

**Issue by trusktr** [sinclairzx81/three-instanced-mesh#1]
Looks like this doesn't support color for each instance yet. That'd be neat.

**Comment by sinclairzx81** [comment]
Hi, Thanks for the suggestion ! 

Just note, this project is more a reference project than a actual library. I mainly wrote it to remind myself how to get instancing working across the standard THREEJS materials than to provide something more concrete. (The documentation on how to do this was a bit sparse when i wrote this project)

Just on the colors though, because the instancing in this project is based around the THREEJS MeshStandardMaterial (I haven't implemented other materials yet), the view here is that each permutation of the MeshStandardMaterial would translate into a separate draw call for each material. (submitting 1x mesh per permutation of the material)...

Consider the following which sets up 3 MeshStandardMaterial's. The colors red, green and blue is set for each. A distinct Mesh is created for each Material permutation, where a mesh will translate into a distinct WebGL draw call (noting the THREEJS Renderer will submit a draw call for each mesh it finds in the scene). This would render 4096 cubes per draw call. (4096 Instances * 3 Meshes == 12288 Cubes)

```typescript
// common geometry
const geometry = new THREE.BoxBufferGeometry(1, 1, 1)

// red material + mesh
const red_material = new THREE.MeshStandardMaterial({ color: 0xFF0000 })
const red_mesh = new InstancedMesh(4096, geometry, red_material) 
for(const instance of red_mesh.instances) {
  instance.position.x = (Math.random() * 16) - 8
  instance.position.y = (Math.random() * 16) - 8
  instance.position.z = (Math.random() * 16) - 8
}
red_mesh.updateInstances()

// green material + mesh
const green_material = new THREE.MeshStandardMaterial({ color: 0x00FF00 })
const green_mesh = new InstancedMesh(4096, geometry, green_material) 
for(const instance of green_mesh.instances) {
  instance.position.x = (Math.random() * 16) - 8
  instance.position.y = (Math.random() * 16) - 8
  instance.position.z = (Math.random() * 16) - 8
}
green_mesh.updateInstances()

// blue material + mesh
const blue_material = new THREE.MeshStandardMaterial({ color: 0x0000FF })
const blue_mesh = new InstancedMesh(4096, geometry, blue_material) 
for(const instance of blue_mesh.instances) {
  instance.position.x = (Math.random() * 16) - 8
  instance.position.y = (Math.random() * 16) - 8
  instance.position.z = (Math.random() * 16) - 8
}
blue_mesh.updateInstances()
```
Of course, it would be possible to set the color for the material as part of the instancing, but doing so would override the default shader pipeline the MeshStandardMaterial. So I haven't gone as far as to extend this library to support that...it also would get tricky by the time you tried to consider things like textures applied to the material.

Again thanks for the suggestion tho, the code is there and you're free to use it. I haven't tested it on the latest THREEJS revisions so mileage may vary if they've changed the shader pipeline recently. However the approach taken here should be fairly easy to port over if required.

Cheers
S

**Comment by sinclairzx81** [comment]
Going to close off this issue. Thanks for the suggestion though. May update this project to use the latest THREEJS builds in the coming months, so keep an eye out for that if you're interested.

Cheers
S
